CREATE DATABASE IF NOT EXISTS formcontact;
USE formcontact;

CREATE TABLE IF NOT EXISTS utilisateurs (
  id INT AUTO_INCREMENT PRIMARY KEY,
  nom_prenoms VARCHAR(30) NOT NULL,
  email VARCHAR(30) NOT NULL UNIQUE,
  contact CHAR(10) NOT NULL CHECK (contact REGEXP '^[0-9]{10}$'),
  domaine_activite VARCHAR(30) NOT NULL,
  date_creation TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
